repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-json
    exclude: (?x)^assets/fonts
  - id: end-of-file-fixer
    exclude: (?x)^assets/fonts
  - id: trailing-whitespace
    exclude: (?x)^assets/fonts
